const budgetServers = [
  {
    name: "Stone Plan",
    name2: "StonePlan",
    ram: "1GB",
    storage: "10GB",
    price: 169,
    original: 249,
    rating: "★★★★☆",
    reviews: 35,
  },
  {
    name: "Coal Plan",
    name2: "CoalPlan",
    ram: "2GB",
    storage: "20GB",
    price: 289,
    original: 419,
    rating: "★★★★☆",
    reviews: 57,
  },
  {
    name: "Iron Plan",
    name2: "IronPlan",
    ram: "3GB",
    storage: "30GB",
    price: 419,
    original: 589,
    rating: "★★★★☆",
    reviews: 82,
  },
  {
    name: "Gold Plan",
    name2: "GoldPlan",
    ram: "4GB",
    storage: "40GB",
    price: 589,
    original: 749,
    rating: "★★★★★",
    reviews: 90,
  },
  {
    name: "Emerald Plan",
    name2: "EmeraldPlan",
    ram: "6GB",
    storage: "60GB",
    price: 829,
    original: 999,
    rating: "★★★★★",
    reviews: 110,
  },
  {
    name: "Diamond Plan",
    name2: "DiamondPlan",
    ram: "8GB",
    storage: "80GB",
    price: 1039,
    original: 1249,
    rating: "★★★★☆",
    reviews: 132,
  },
  {
    name: "Netherite Plan",
    name2: "NetheritePlan",
    ram: "10GB",
    storage: "100GB",
    price: 1329,
    original: 1579,
    rating: "★★★★★",
    reviews: 145,
  },
  {
    name: "Obsidian Plan",
    name2: "ObsidianPlan",
    ram: "12GB",
    storage: "120GB",
    price: 1539,
    original: 1829,
    rating: "★★★★★",
    reviews: 158,
  },
];

const premiumServers = [
  {
    name: "Titanium Plan",
    name2: "TitaniumPlan",
    ram: "16GB",
    storage: "200GB NVMe",
    price: 2079,
    original: 2499,
    rating: "★★★★★",
    reviews: 198,
  },
  {
    name: "Platinum Plan",
    name2: "PlatinumPlan",
    ram: "24GB",
    storage: "300GB NVMe",
    price: 2909,
    original: 3329,
    rating: "★★★★★",
    reviews: 176,
  },
  {
    name: "Galaxy Plan",
    name2: "GalaxyPlan",
    ram: "32GB",
    storage: "500GB NVMe",
    price: 3749,
    original: 4159,
    rating: "★★★★★",
    reviews: 222,
  },
  {
    name: "Quantum Plan",
    name2: "QuantumPlan",
    ram: "48GB",
    storage: "750GB NVMe",
    price: 4999,
    original: 5499,
    rating: "★★★★★",
    reviews: 260,
  },
  {
    name: "Cosmic Plan",
    name2: "CosmicPlan",
    ram: "64GB",
    storage: "1TB NVMe",
    price: 6659,
    original: 7489,
    rating: "★★★★★",
    reviews: 300,
  },
  {
    name: "Nebula Plan",
    name2: "NebulaPlan",
    ram: "80GB",
    storage: "1.5TB NVMe",
    price: 8319,
    original: 9149,
    rating: "★★★★★",
    reviews: 340,
  },
  {
    name: "Void Plan",
    name2: "VoidPlan",
    ram: "96GB",
    storage: "2TB NVMe",
    price: 9979,
    original: 11649,
    rating: "★★★★★",
    reviews: 380,
  },
  {
    name: "Eclipse Plan",
    name2: "EclipsePlan",
    ram: "128GB",
    storage: "4TB NVMe",
    price: 12479,
    original: 14139,
    rating: "★★★★★",
    reviews: 410,
  },
];

const proVPS = [
  {
    name: "VPS Starter",
    name2: "VPSStarter",
    ram: "4GB",
    storage: "80GB SSD",
    price: 1249,
    original: 1669,
    rating: "★★★★☆",
    reviews: 120,
  },
  {
    name: "VPS Boost",
    name2: "VPSBoost",
    ram: "8GB",
    storage: "160GB SSD",
    price: 1669,
    original: 2079,
    rating: "★★★★☆",
    reviews: 150,
  },
  {
    name: "VPS Turbo",
    name2: "VPSTurbo",
    ram: "16GB",
    storage: "320GB SSD",
    price: 2499,
    original: 2909,
    rating: "★★★★★",
    reviews: 180,
  },
  {
    name: "VPS Ultra",
    name2: "VPSUltra",
    ram: "32GB",
    storage: "640GB SSD",
    price: 4159,
    original: 4999,
    rating: "★★★★★",
    reviews: 200,
  },
  {
    name: "VPS Titan",
    name2: "VPSTitan",
    ram: "48GB",
    storage: "960GB SSD",
    price: 5829,
    original: 6659,
    rating: "★★★★★",
    reviews: 230,
  },
  {
    name: "VPS Cosmic",
    name2: "VPSCosmic",
    ram: "64GB",
    storage: "1.2TB SSD",
    price: 7489,
    original: 8319,
    rating: "★★★★★",
    reviews: 260,
  },
  {
    name: "VPS Warp",
    name2: "VPSWarp",
    ram: "80GB",
    storage: "1.5TB SSD",
    price: 8649,
    original: 9979,
    rating: "★★★★★",
    reviews: 300,
  },
  {
    name: "VPS Infinity",
    name2: "VPSInfinity",
    ram: "128GB",
    storage: "2TB SSD",
    price: 11649,
    original: 12479,
    rating: "★★★★★",
    reviews: 340,
  },
];

const ultraVPS = [
  {
    name: "Ultra Core",
    name2: "UltraCore",
    ram: "8GB",
    storage: "200GB NVMe",
    price: 2079,
    original: 2499,
    rating: "★★★★☆",
    reviews: 140,
  },
  {
    name: "Ultra Boost",
    name2: "UltraBoost",
    ram: "16GB",
    storage: "400GB NVMe",
    price: 3329,
    original: 3749,
    rating: "★★★★☆",
    reviews: 180,
  },
  {
    name: "Ultra Max",
    name2: "UltraMax",
    ram: "32GB",
    storage: "800GB NVMe",
    price: 4999,
    original: 5829,
    rating: "★★★★★",
    reviews: 220,
  },
  {
    name: "Ultra Titan",
    name2: "UltraTitan",
    ram: "64GB",
    storage: "1.2TB NVMe",
    price: 7069,
    original: 7899,
    rating: "★★★★★",
    reviews: 270,
  },
  {
    name: "Ultra Supreme",
    name2: "UltraSupreme",
    ram: "96GB",
    storage: "1.6TB NVMe",
    price: 7569,
    original: 10399,
    rating: "★★★★★",
    reviews: 320,
  },
  {
    name: "Ultra Nova",
    name2: "UltraNova",
    ram: "128GB",
    storage: "2TB NVMe",
    price: 11649,
    original: 12479,
    rating: "★★★★★",
    reviews: 360,
  },
  {
    name: "Ultra Warp",
    name2: "UltraWarp",
    ram: "160GB",
    storage: "2.5TB NVMe",
    price: 14139,
    original: 14999,
    rating: "★★★★★",
    reviews: 400,
  },
  {
    name: "Ultra Infinite",
    name2: "UltraInfinite",
    ram: "192GB",
    storage: "3TB NVMe",
    price: 16399,
    original: 17469,
    rating: "★★★★★",
    reviews: 450,
  },
];

const domains = [
  {
    name: "yourname.com",
    price: 999,
    extension: ".com",
    popularity: "Popular",
    reviews: 120,
  },
  {
    name: "yourbrand.net",
    price: 839,
    extension: ".net",
    popularity: "Trusted",
    reviews: 85,
  },
  {
    name: "coolorg.org",
    price: 919,
    extension: ".org",
    popularity: "Reliable",
    reviews: 70,
  },
  {
    name: "techie.dev",
    price: 1249,
    extension: ".dev",
    popularity: "Trending",
    reviews: 140,
  },
  {
    name: "startup.xyz",
    price: 589,
    extension: ".xyz",
    popularity: "Newbie Fav",
    reviews: 65,
  },
  {
    name: "gamehub.gg",
    price: 2499,
    extension: ".gg",
    popularity: "Gamer Pick",
    reviews: 200,
  },
];

const developers = [
  {
    name: "Alex Carter",
    role: "Minecraft Plugin Developer",
    price: "$20 - $50/hr",
    desc: "Expert in Bukkit/Spigot plugin development and server optimization.",
    img: "https://i.pravatar.cc/100?img=1",
  },
  {
    name: "Lena Kim",
    role: "Web UI/UX Designer",
    price: "$25 - $60/hr",
    desc: "Designs responsive, neon-themed dashboards and control panels.",
    img: "https://i.pravatar.cc/100?img=2",
  },
  {
    name: "Ethan Voss",
    role: "Full Stack Game Dev",
    price: "$30 - $80/hr",
    desc: "Experienced in backend and frontend for Minecraft & Rust server shops.",
    img: "https://i.pravatar.cc/100?img=3",
  },
  {
    name: "Sasha Rivera",
    role: "JavaScript Scripting Expert",
    price: "$15 - $45/hr",
    desc: "Automates server systems, mods, and control interfaces.",
    img: "https://i.pravatar.cc/100?img=4",
  },
  {
    name: "Jaden Lin",
    role: "Backend Infrastructure Engineer",
    price: "$35 - $90/hr",
    desc: "DevOps, scalable infrastructure for multiplayer servers.",
    img: "https://i.pravatar.cc/100?img=5",
  },
];

export { budgetServers, premiumServers, proVPS, ultraVPS, domains, developers };
